services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tc1-repairshop-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - tc1-repairshop-network

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tc1-repairshop-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TC1RepairShop;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"

      Jwt__Secret: "${JWT_SECRET}"
      Jwt__Issuer: "TC1.RepairShop"
      Jwt__Audience: "TC1.RepairShop.Clients"
      Jwt__ExpirationMinutes: "${Jwt_ExpirationMinutes}"
      
      SeedAdmin__Username: "${SeedAdmin_Username}"
      SeedAdmin__Password: "${SeedAdmin_Password}"
      SeedAdmin__Email: "${SeedAdmin_EMAIL}"
      SeedAdmin__Document: "${SeedAdmin_DOCUMENT}"
      SeedAdmin__Phone: "${SeedAdmin_PHONE}"

      SendGrid__ApiKey: "${SENDGRID_API_KEY}"
      SendGrid__FromEmail: "${SENDGRID_FROM_EMAIL}"
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - tc1-repairshop-network

networks:
  tc1-repairshop-network:
    driver: bridge

volumes:
  sqlserver_data: